spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: microservicloud-config-jingtu-dev

---
spring:
  profiles: test
  application:
    name: microservicloud-config-jingtu-test