spring:
  profiles:
    active:
    - dev
---
server:
  port: 8070
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-consumer-dept
    
feign:
  hystrix:
    enabled: true

# 配置eureka
eureka:
  client:
    #register-with-eureka: false
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept.com
    prefer-ip-address: true   

---
server:
  port: 8070
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-consumer-dept
    
feign:
  hystrix:
    enabled: true

# 配置eureka
eureka:
  client:
    #register-with-eureka: false
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept.com
    prefer-ip-address: true       